const bowlingLanesArray = [
  { activity_typeid: 1, id: 1, activity_name: "Bowlingbane 1" },
  { activity_type_id: 1, id: 2, activity_name: "Bowlingbane 2" },
  { activity_type_id: 1, id: 3, activity_name: "Bowlingbane 3" },
  { activity_type_id: 1, id: 4, activity_name: "Bowlingbane 4" },
  { activity_type_id: 1, id: 5, activity_name: "Bowlingbane 5" },
  { activity_type_id: 1, id: 6, activity_name: "Bowlingbane 6" },
  { activity_type_id: 1, id: 7, activity_name: "Bowlingbane 7" },
  { activity_type_id: 1, id: 8, activity_name: "Bowlingbane 8" },
  { activity_type_id: 1, id: 9, activity_name: "Bowlingbane 9" },
  { activity_type_id: 1, id: 10, activity_name: "Bowlingbane 10" },
  { activity_type_id: 1, id: 11, activity_name: "Bowlingbane 11" },
  { activity_type_id: 1, id: 12, activity_name: "Bowlingbane 12" },
  { activity_type_id: 1, id: 13, activity_name: "Bowlingbane 13" },
  { activity_type_id: 1, id: 14, activity_name: "Bowlingbane 14" },
  { activity_type_id: 1, id: 15, activity_name: "Bowlingbane 15" },
  { activity_type_id: 1, id: 16, activity_name: "Bowlingbane 16" },
  { activity_type_id: 1, id: 17, activity_name: "Bowlingbane 17" },
  { activity_type_id: 1, id: 18, activity_name: "Bowlingbane 18" },
  { activity_type_id: 1, id: 19, activity_name: "Bowlingbane 19" },
  { activity_type_id: 1, id: 20, activity_name: "Bowlingbane 20" },
];

const kidsBowlingLanesArray = [
  { activity_type_id: 2, id: 21, activity_name: "Bowlingbane 21" },
  { activity_type_id: 2, id: 22, activity_name: "Bowlingbane 22" },
  { activity_type_id: 2, id: 23, activity_name: "Bowlingbane 23" },
  { activity_type_id: 2, id: 24, activity_name: "Bowlingbane 24" },
];

const airhockyTablesArray = [
  { activity_type_id: 3, id: 25, activity_name: "Airhockeybord 1" },
  { activity_type_id: 3, id: 26, activity_name: "Airhockeybord 2" },
  { activity_type_id: 3, id: 27, activity_name: "Airhockeybord 3" },
  { activity_type_id: 3, id: 28, activity_name: "Airhockeybord 4" },
  { activity_type_id: 3, id: 29, activity_name: "Airhockeybord 5" },
  { activity_type_id: 3, id: 30, activity_name: "Airhockeybord 6" },
];

const dinnerTablesArray = [
  { activity_type_id: 4, id: 31, activity_name: "Bord 1" },
  { activity_type_id: 4, id: 32, activity_name: "Bord 2" },
  { activity_type_id: 4, id: 33, activity_name: "Bord 3" },
  { activity_type_id: 4, id: 34, activity_name: "Bord 4" },
  { activity_type_id: 4, id: 35, activity_name: "Bord 5" },
  { activity_type_id: 4, id: 36, activity_name: "Bord 6" },
  { activity_type_id: 4, id: 37, activity_name: "Bord 7" },
  { activity_type_id: 4, id: 38, activity_name: "Bord 8" },
  { activity_type_id: 4, id: 39, activity_name: "Bord 9" },
  { activity_type_id: 4, id: 40, activity_name: "Bord 10" },
  { activity_type_id: 4, id: 41, activity_name: "Bord 11" },
  { activity_type_id: 4, id: 42, activity_name: "Bord 12" },
  { activity_type_id: 4, id: 43, activity_name: "Bord 13" },
  { activity_type_id: 4, id: 44, activity_name: "Bord 14" },
  { activity_type_id: 4, id: 45, activity_name: "Bord 15" },
  { activity_type_id: 4, id: 46, activity_name: "Bord 16" },
  { activity_type_id: 4, id: 47, activity_name: "Bord 17" },
  { activity_type_id: 4, id: 48, activity_name: "Bord 18" },
  { activity_type_id: 4, id: 49, activity_name: "Bord 19" },
  { activity_type_id: 4, id: 50, activity_name: "Bord 20" },
  { activity_type_id: 4, id: 51, activity_name: "Bord 21" },
  { activity_type_id: 4, id: 52, activity_name: "Bord 22" },
  { activity_type_id: 4, id: 53, activity_name: "Bord 23" },
  { activity_type_id: 4, id: 54, activity_name: "Bord 24" },
  { activity_type_id: 4, id: 55, activity_name: "Bord 25" },
  { activity_type_id: 4, id: 56, activity_name: "Bord 26" },
  { activity_type_id: 4, id: 57, activity_name: "Bord 27" },
  { activity_type_id: 4, id: 58, activity_name: "Bord 28" },
  { activity_type_id: 4, id: 59, activity_name: "Bord 29" },
  { activity_type_id: 4, id: 60, activity_name: "Bord 30" },
  { activity_type_id: 4, id: 61, activity_name: "Bord 31" },
  { activity_type_id: 4, id: 62, activity_name: "Bord 32" },
  { activity_type_id: 4, id: 63, activity_name: "Bord 33" },
  { activity_type_id: 4, id: 64, activity_name: "Bord 34" },
  { activity_type_id: 4, id: 65, activity_name: "Bord 35" },
  { activity_type_id: 4, id: 66, activity_name: "Bord 36" },
  { activity_type_id: 4, id: 67, activity_name: "Bord 37" },
  { activity_type_id: 4, id: 68, activity_name: "Bord 38" },
  { activity_type_id: 4, id: 69, activity_name: "Bord 39" },
  { activity_type_id: 4, id: 70, activity_name: "Bord 40" },
  { activity_type_id: 4, id: 71, activity_name: "Bord 41" },
  { activity_type_id: 4, id: 72, activity_name: "Bord 42" },
  { activity_type_id: 4, id: 73, activity_name: "Bord 43" },
  { activity_type_id: 4, id: 74, activity_name: "Bord 44" },
  { activity_type_id: 4, id: 75, activity_name: "Bord 45" },
  { activity_type_id: 4, id: 76, activity_name: "Bord 46" },
  { activity_type_id: 4, id: 77, activity_name: "Bord 47" },
  { activity_type_id: 4, id: 78, activity_name: "Bord 48" },
  { activity_type_id: 4, id: 79, activity_name: "Bord 49" },
  { activity_type_id: 4, id: 80, activity_name: "Bord 59" },
];

export {
  bowlingLanesArray,
  kidsBowlingLanesArray,
  airhockyTablesArray,
  dinnerTablesArray,
};
